Clusterpool
AdrianHammond/multicluster-devsecops-op-res pull request #2
Opened 2023-11-16 18:04 UTC by r2dedios

2023-11-16 23:16 UTC, TomerFi requested changes

2023-11-16 23:16 UTC, TomerFi commented on values-hub.yaml
> +          install-config: "ESTO ES UNA PRUEBA"
Perhaps we should add some info about the target install config in a comment here.

2023-11-17 09:43 UTC, r2dedios commented on common/acm/templates/provision/clusterpool.yaml
> +    name: {{ $poolName }}-install-config
you're right, It was my editor. Removing it

2023-11-17 09:46 UTC, r2dedios commented on values-hub.yaml
> +          install-config: "ESTO ES UNA PRUEBA"
oh sorry, it was a comment for testing the install-config creationg. Removed.

2023-11-17 17:53 UTC, r2dedios commented
Updated changes of our last talk @TomerFi

2023-11-17 18:39 UTC, TomerFi approved these changes
LGTM

Merging.

2023-11-17 18:41 UTC, merged